### ISSUE TITLE
If SelectedItem is only bind and Items have the same name, selection is messed up on first focus

### ISSUE THREAD

**Issue by puppetsw** [puppetsw/AvaloniaTokenizingTextBox#2]

**Comment by puppetsw** [comment]
Something to do with the SelectedItem binding. Removing the binding in the view fixes the issue.
Issue occurs with normal ListBoxs from Avalonia.

#### View.xaml
```xml
<StackPanel>
   <ListBox Items="{Binding List1}" SelectedItem="{Binding SelectedItem}" />
   <ListBox Items="{Binding List1}" />
</StackPanel>
```

#### ViewModel.cs
```cs
public ObservableCollection<string> List1 { get; set; }
public string SelectedItem { get; set; }
public MainWindowViewModel()
{
  List1 = new ObservableCollection<string>();
  List1.Add("Test");
  List1.Add("Test");
  List1.Add("Test");
}
```

**Comment by asyagelski** [comment]
Just tested this. Using ``SelectionModel<string>`` bound to ``ListBox.Selection`` instead of binding to ``ListBox.SelectedItem`` directly seems to fix this issue.

Edit: Then you can bind to ``Selection.SelectedItem`` which returns "Test".

**Comment by puppetsw** [comment]
Interesting... thanks for taking the time to look at this. 

Edit: I noticed stepping through the code, the SelectedIndex seems to be getting set twice in the SelectionModel. First time through the index is correct, but then it gets set to 0 for some reason.

**Comment by asyagelski** [comment]
Hm... I pulled it up again and unless I'm missing something or going crazy, I can't seem to replicate the issue we both noticed. I bound a ``TextBlock`` directly to ``ListBox.SelectedItem``, I bound them both to a string property in the viewmodel, and I bound them both to a ``SelectionModel<string>`` object. They all behave correctly! Are you updated to the latest version of both Avalonia and the VisualStudio extension? Any ideas to reproduce the issue?

**Comment by puppetsw** [comment]
I don’t think I have the latest build. I’ll update and report back. 

Edit: I just updated to 0.10.6 and the issue persists in my project. I might try a new one and see if it's still the same there. 
Edit 2: I created a basic project, with just a ListBox, a ObservableCollection<string> and string SelectedItem. The issue exists for me with just the Items and SelectedItem bound to the ListBox. 

Stepping through the SelectionModel code. The SelectedItem is set correctly, until the SelectedIndex is set afterwards. 

![image](https://user-images.githubusercontent.com/79826944/121442470-e8b9ce80-c9ca-11eb-8c33-3b827c0a4cd9.png)

**Comment by asyagelski** [comment]
Hm... Is my setup any different from yours?
![ListBoxShenanigans](https://user-images.githubusercontent.com/8888989/121558098-596ce500-c9e3-11eb-9ecb-96d1c8fab3f7.png)

**Comment by puppetsw** [comment]
I don't have the binding for SelectedIndex. If I add that to mine, it solves the issue. But the issue still persists for me if only the SelectedItem is bound to. The issue is only there while the SelectedItem on the ListBox is not null (so after the first click it works correctly)
![Example1](https://user-images.githubusercontent.com/79826944/121601797-95f11d00-ca85-11eb-9b69-96066dd8c1c1.gif)
![image](https://user-images.githubusercontent.com/79826944/121602044-e23c5d00-ca85-11eb-9e0f-a3e7506045c8.png)

I've been doing some more investigation on this. It appears that the line in Avalonia SelectionModel.cs might be causing the issue.
```csharp
public T SelectedItem {
  get 
  {
    if (ItemsView is object) 
    {
      return GetItemAt(_selectedIndex);
    }
    else if (_initSelectedItems is object && _initSelectedItems.Count > 0) {
      return (T) _initSelectedItems[0];
    }

    return default;
  }
  set 
  {
    if (ItemsView is object) 
    {
      SelectedIndex = ItemsView.IndexOf(value ! ); //<----- This line here.
    }
    else 
    {
      Clear();#pragma warning disable CS8601
      SetInitSelectedItems(new T[] {
        value
      });#pragma warning restore CS8601
    }
  }
}
```
Commenting it out fixes the issue, but it makes the following tests fail
* Focusing_Item_With_Ctrl_And_Arrow_Key_Should_Add_To_Selection
* Focusing_Item_With_Ctrl_And_Arrow_Key_Should_Add_To_Selection
* SelectedItem_Should_Not_Cause_StackOverflow

I might just make my control not allow duplicates, it would solve the issue without needing to figure out what's going on here.

The bug only happens when the List is bound to a collection of string, int, double, etc. collections of objects works as intended.
